<?php

namespace Qarbi\SensitiveConfigurationSet\Console\Command;

use Magento\Config\Console\Command\ConfigSet\ProcessorFacadeFactory;
use Magento\Config\Console\Command\EmulatedAdminhtmlAreaProcessor;
use Magento\Deploy\Model\DeploymentConfig\ChangeDetector;
use Magento\Framework\App\DeploymentConfig;
use Magento\Framework\Encryption\EncryptorInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigSetSensitiveCommand extends \Magento\Config\Console\Command\ConfigSetCommand
{
    private EncryptorInterface $encryptor;

    public function __construct(
        EmulatedAdminhtmlAreaProcessor $emulatedAreaProcessor,
        ChangeDetector $changeDetector,
        ProcessorFacadeFactory $processorFacadeFactory,
        DeploymentConfig $deploymentConfig,
        EncryptorInterface $encryptor
    )
    {
        $this->encryptor = $encryptor;
        parent::__construct($emulatedAreaProcessor, $changeDetector, $processorFacadeFactory, $deploymentConfig);
    }

    protected function configure()
    {
        parent::configure();
        $this->setName('config:set:qarbi_sensitive')
            ->setDescription('Change system configuration with qarbi sensitive');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $value = $input->getArgument(static::ARG_VALUE);
        $encryptValue = $this->encryptor->encrypt($value);
        $input->setArgument(self::ARG_VALUE, $encryptValue);
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
